=== z1230601/BAKK_Prodanovic_Zaric_OBD/cfg/obdcommand.dtd
<!ELEMENT servicemodes (servicemode+)>
<!ELEMENT servicemode ((sid+), (obdcommands?))>
<!ELEMENT obdcommands ((obdcommand+))>
<!ELEMENT obdcommand (pid, description, (validitymapping?), values)>
<!ELEMENT values ((value+))>
<!ELEMENT value ( (name, bytes, min, max, unit,(validitybit?)) | (bytes, mapping) )>
<!ELEMENT mapping (((entry*), (validitybit*))*)>

<!ELEMENT entry (#PCDATA)>
<!ELEMENT validitymapping (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT pid (#PCDATA)>
<!ELEMENT sid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT bytes (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT validitybit (#PCDATA)>


<!ATTLIST entry from CDATA #REQUIRED>
<!ATTLIST entry set CDATA #IMPLIED>
<!ATTLIST validitybit from CDATA #IMPLIED>
<!ATTLIST mapping type (bit|value|bitcombination) "bit">
<!ATTLIST value interpretation (calculation|mapping) "calculation">
<!ATTLIST validitymapping mode (manual|auto|off) "off">

=== z1230601/BAKK_Prodanovic_Zaric_OBD/OBDMiddleware/configurations/test/testdata/obdcommand.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE servicemodes SYSTEM "obdcommand.dtd">
<servicemodes>
	<servicemode>
		<sid>1</sid>
		<sid>2</sid>
		<obdcommands>
			<!-- PID 00 -->
			<obdcommand>
				<pid>00</pid>
				<description>Unterstützte PIDs im Bereich 01-20</description>
				<validitymapping mode="auto">true</validitymapping>
				<values>
					<value interpretation="mapping">
					<bytes>4</bytes>
						<mapping type="bit">
						    <entry from="0" set="false">PID 01 nicht unterstützt</entry>
							<entry from="0" set="true">PID 01 unterstützt</entry>
							<entry from="1" set="false">PID 02 nicht unterstützt</entry>
							<entry from="1" set="true">PID 02 unterstützt</entry>
							<entry from="2" set="false">PID 03 nicht unterstützt</entry>
							<entry from="2" set="true">PID 03 unterstützt</entry>
							<entry from="3" set="false">PID 04 nicht unterstützt</entry>
							<entry from="3" set="true">PID 04 unterstützt</entry>
							<entry from="4" set="false">PID 05 nicht unterstützt</entry>
							<entry from="4" set="true">PID 05 unterstützt</entry>
							<entry from="5" set="false">PID 06 nicht unterstützt</entry>
							<entry from="5" set="true">PID 06 unterstützt</entry>
							<entry from="6" set="false">PID 07 nicht unterstützt</entry>
							<entry from="6" set="true">PID 07 unterstützt</entry>
							<entry from="7" set="false">PID 08 nicht unterstützt</entry>
							<entry from="7" set="true">PID 08 unterstützt</entry>
							<entry from="8" set="false">PID 09 nicht unterstützt</entry>
							<entry from="8" set="true">PID 09 unterstützt</entry>
							<entry from="9" set="false">PID 0A nicht unterstützt</entry>
							<entry from="9" set="true">PID 0A unterstützt</entry>
							<entry from="10" set="false">PID 0B nicht unterstützt</entry>
							<entry from="10" set="true">PID 0B unterstützt</entry>
							<entry from="11" set="false">PID 0C nicht unterstützt</entry>
							<entry from="11" set="true">PID 0C unterstützt</entry>
							<entry from="12" set="false">PID 0D nicht unterstützt</entry>
							<entry from="12" set="true">PID 0D unterstützt</entry>
							<entry from="13" set="false">PID 0E nicht unterstützt</entry>
							<entry from="13" set="true">PID 0E unterstützt</entry>
							<entry from="14" set="false">PID 0F nicht unterstützt</entry>
							<entry from="14" set="true">PID 0F unterstützt</entry>
							<entry from="15" set="false">PID 10 nicht unterstützt</entry>
							<entry from="15" set="true">PID 10 unterstützt</entry>
							<entry from="16" set="false">PID 11 nicht unterstützt</entry>
							<entry from="16" set="true">PID 11 unterstützt</entry>
							<entry from="17" set="false">PID 12 nicht unterstützt</entry>
							<entry from="17" set="true">PID 12 unterstützt</entry>
							<entry from="18" set="false">PID 13 nicht unterstützt</entry>
							<entry from="18" set="true">PID 13 unterstützt</entry>
							<entry from="19" set="false">PID 14 nicht unterstützt</entry>
							<entry from="19" set="true">PID 14 unterstützt</entry>
							<entry from="20" set="false">PID 15 nicht unterstützt</entry>
							<entry from="20" set="true">PID 15 unterstützt</entry>
							<entry from="21" set="false">PID 16 nicht unterstützt</entry>
							<entry from="21" set="true">PID 16 unterstützt</entry>
							<entry from="22" set="false">PID 17 nicht unterstützt</entry>
							<entry from="22" set="true">PID 17 unterstützt</entry>
							<entry from="23" set="false">PID 18 nicht unterstützt</entry>
							<entry from="23" set="true">PID 18 unterstützt</entry>
							<entry from="24" set="false">PID 19 nicht unterstützt</entry>
							<entry from="24" set="true">PID 19 unterstützt</entry>
							<entry from="25" set="false">PID 1A nicht unterstützt</entry>
							<entry from="25" set="true">PID 1A unterstützt</entry>
							<entry from="26" set="false">PID 1B nicht unterstützt</entry>
							<entry from="26" set="true">PID 1B unterstützt</entry>
							<entry from="27" set="false">PID 1C nicht unterstützt</entry>
							<entry from="27" set="true">PID 1C unterstützt</entry>
							<entry from="28" set="false">PID 1D nicht unterstützt</entry>
							<entry from="28" set="true">PID 1D unterstützt</entry>
							<entry from="29" set="false">PID 1E nicht unterstützt</entry>
							<entry from="29" set="true">PID 1E unterstützt</entry>
							<entry from="30" set="false">PID 1F nicht unterstützt</entry>
							<entry from="30" set="true">PID 1F unterstützt</entry>
							<entry from="31" set="false">PID 20 nicht unterstützt</entry>
							<entry from="31" set="true">PID 20 unterstützt</entry>
						</mapping>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>01</pid>
				<description>Systemstatus (Readiness Code), MIL</description>
				<validitymapping></validitymapping>
				<values>
					<value>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>02</pid>
				<description>DTC, der Abspeicherung von Freeze Frame Daten auslöste</description>
				<validitymapping>true</validitymapping>
				<values>
					<value interpretation="calculation">
						<name>DTC</name>
						<bytes>2</bytes>
						<min>0</min>
						<max>65535</max>
						<unit></unit>	
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>03</pid>
				<description>Status Einspritzsystem System 1 und 2</description>
				<validitymapping>false</validitymapping>
				<values>
					<value interpretation="mapping">
						<bytes>2</bytes>
						<mapping type="bit">
							<!-- System 1 -->
							<entry from="0">Offener Kreislauf (hat noch nicht die Bedingungen erfüllt, um den Kreislauf zu schließen</entry>
							<entry from="1">Geschlossener Kreislauf</entry>
							<entry from="2">Geschlossener Kreislauf (bedingt durch Fahrverhalten)</entry>
							<entry from="3">Offener Kreislauf (wegen Fehler)</entry>
							<entry from="4">Geschlossener Kreislauf (aber Fehler)</entry>
							<!-- <entry from="5-7">Reserviert</entry> -->
							<!-- System 2 -->
							<entry from="8">Offener Kreislauf (hat noch nicht die Bedingungen erfüllt, um den Kreislauf zu schließen</entry>
							<entry from="9">Geschlossener Kreislauf</entry>
							<entry from="10">Geschlossener Kreislauf (bedingt durch Fahrverhalten)</entry>
							<entry from="11">Offener Kreislauf (wegen Fehler)</entry>
							<entry from="12">Geschlossener Kreislauf (aber Fehler)</entry>
							<!-- <entry from="13-15">Reserviert</entry> -->
						</mapping>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>04</pid>
				<description>Motorlast (berechnet)</description>
				<values>
					<value interpretation="calculation">
						<name>Motorlast</name>
						<bytes>1</bytes>
						<min>0</min>
						<max>100</max>
						<unit>%</unit>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>05</pid>
				<description>Kühlmitteltemperatur</description>
				<values>
					<value interpretation="calculation">
						<name>Kühlmitteltemperatur</name>
						<bytes>1</bytes>
						<min>-40</min>
						<max>215</max>
						<unit>°C</unit>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>06</pid>
				<description>Kurzzeitige Kraftstoff-Einspritz-Korrektur Bank 1, Bank 3</description>
				<values>
					<value interpretation="calculation">
						<name>Bank 1</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
					<!-- Nur geliefert wenn vom Fahrzeug unterstützt (anhand PID 1D feststellbar) -->
					<value interpretation="calculation">
						<name>Bank 3</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>07</pid>
				<description>Langfristige Kraftstoff-Einspritz-Korrektur Bank 1, Bank 3</description>
				<values>
					<value interpretation="calculation">
						<name>Bank 1</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
					<!-- Nur geliefert wenn vom Fahrzeug unterstützt (anhand PID 1D feststellbar) -->
					<value interpretation="calculation">
						<name>Bank 3</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>08</pid>
				<description>Kurzzeitige Kraftstoff-Einspritz-Korrektur Bank 2, Bank 4</description>
				<values>
					<value interpretation="calculation">
						<name>Bank 2</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
					<!-- Nur geliefert wenn vom Fahrzeug unterstützt (anhand PID 1D feststellbar) -->
					<value interpretation="calculation">
						<name>Bank 4</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>09</pid>
				<description>Langfristige Kraftstoff-Einspritz-Korrektur Bank 2, Bank 4</description>
				<values>
					<value interpretation="calculation">
						<name>Bank 2</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
					<!-- Nur geliefert wenn vom Fahrzeug unterstützt (anhand PID 1D feststellbar) -->
					<value interpretation="calculation">
						<name>Bank 4</name>
						<bytes>1</bytes>
						<min>-100</min>
						<max>99.22</max>
						<unit>%</unit>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>0A</pid>
				<description>Kraftstoffdruck an der Kraftstoffverteilerleiste relativ zur Umgebungsatmosphäre</description>
				<values>
					<value interpretation="calculation">
						<name>Kraftstoffdruck</name>
						<bytes>1</bytes>
						<min>0</min>
						<max>765</max>
						<unit>kPa</unit>
					</value>
				</values>
			</obdcommand>
			<obdcommand>
				<pid>0B</pid>
				<description>Absolutdruck Ansaugrohr</description>
				<values>
